name: Static and unit tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - "wheel/**"
      - "runci/**"
  release:
    types:
      - created
      - edited
  schedule:
    # 04:00 every Tuesday morning
    - cron: "0 4 * * 2"

jobs:
  static-checks:
    name: Static tests
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        pyver: ["3.12"]
    uses: Quantinuum/pytket-workflows/.github/workflows/static-checks-wf.yml@v1
    with:
      os: ${{ matrix.os }}
      pyver: ${{ matrix.pyver }}

  unit-tests:
    name: Unit tests
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        pyver: ["3.10", "3.13"]
    uses: Quantinuum/pytket-workflows/.github/workflows/unit-test-wf.yml@v1
    with:
      os: ${{ matrix.os }}
      pyver: ${{ matrix.pyver }}

  remote-tests:
    name: Remote Unit tests
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        pyver: ["3.11"]
    uses: Quantinuum/pytket-workflows/.github/workflows/unit-test-remote-wf.yml@v1
    with:
      os: ${{ matrix.os }}
      pyver: ${{ matrix.pyver }}
    secrets:
      PYTKET_REMOTE_BRAKET_ACCESS_KEY_ID: ${{ secrets.PYTKET_REMOTE_BRAKET_ACCESS_KEY_ID }}
      PYTKET_REMOTE_BRAKET_ACCESS_KEY_SECRET: ${{ secrets.PYTKET_REMOTE_BRAKET_ACCESS_KEY_SECRET }}
      PYTKET_REMOTE_BRAKET_REGION: ${{ secrets.PYTKET_REMOTE_BRAKET_REGION }}
      PYTKET_REMOTE_BRAKET_BUCKET: ${{ secrets.PYTKET_REMOTE_BRAKET_BUCKET }}
      PYTKET_REMOTE_BRAKET_FOLDER: ${{ secrets.PYTKET_REMOTE_BRAKET_FOLDER }}
